In [2]:
import torch
torch.__version__

'1.13.0'

## 创建数组

In [3]:
# 创建一维数组
import numpy as np
arr_1_d = np.asarray([1])
print(arr_1_d)

[1]


In [4]:
# 创建二维数组
arr_2_d = np.asarray([[1, 2], [3, 4]])
print(arr_2_d)

[[1 2]
 [3 4]]


In [5]:
arr_1_d.ndim

1

In [6]:
arr_2_d.ndim

2

In [7]:
arr_1_d.shape

(1,)

In [8]:
arr_2_d.shape

(2, 2)

In [9]:
## 数组形状变换

In [10]:
arr_2_d.shape

(2, 2)

In [11]:
arr_2_d

array([[1, 2],
       [3, 4]])

In [12]:
arr_2_d.reshape((4,1))

array([[1],
       [2],
       [3],
       [4]])

In [13]:
a = np.arange(6).reshape(2,3)
print(a)

[[0 1 2]
 [3 4 5]]


In [14]:
## Pillow方式加载图片

In [15]:
from PIL import Image
im = Image.open('jk.jpg')
im.size

(318, 116)

In [16]:
## 图片二进制转为 NumPy 格式

In [17]:
im_pillow = np.asarray(im)
im_pillow.shape

(116, 318, 3)

In [18]:
## OpenCV方式加载图片

In [19]:
import cv2
im_cv2 = cv2.imread('jk.jpg')
type(im_cv2)

numpy.ndarray

In [20]:
im_cv2.shape

(116, 318, 3)

In [21]:
im_pillow[:, :, 0]

array([[255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       ...,
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255]], dtype=uint8)

In [22]:
im_pillow_c1 = im_pillow[:, :, 0]
im_pillow_c2 = im_pillow[:, :, 1]
im_pillow_c3 = im_pillow[:, :, 2]

In [23]:
zeros = np.zeros((im_pillow.shape[0], im_pillow.shape[1], 2))
zeros.shape

(116, 318, 2)

In [24]:
im_pillow_c1_3ch = np.concatenate((im_pillow_c1, zeros), axis=2)

AxisError: axis 2 is out of bounds for array of dimension 2

In [25]:
im_pillow_c1.shape

(116, 318)

In [26]:
zeros.shape

(116, 318, 2)

In [27]:
im_pillow_c1 = im_pillow_c1[:, :, np.newaxis]

In [28]:
im_pillow_c1.shape

(116, 318, 1)

In [29]:
im_pillow_c1_3ch = np.concatenate((im_pillow_c1, zeros), axis=2)
im_pillow_c1_3ch.shape

(116, 318, 3)